MAX_MARKET_CAP_EUR: 210000
SCAN_INTERVAL_HOURS: 6
DRY_RUN: false

RATIO_WEIGHTS:
  mc_fdv: 12
  liquidity_ratio: 18
  circ_vs_total: 8
  contract_verified: 20
  lp_locked: 15
  blacklisted: -30
  antiscam: -50

ENABLED_SOURCES:
  - binance_launchpad
  - coinlist
  - polkastarter
  # ... (39 autres sources)
